- name: Container runtime setup
  include_tasks: containerd.yml

- name: Kubernetes prerequisites
  include_tasks: prerequisites.yml

- name: Install Podman
  apt:
    name: podman
    state: present

- name: Disable UFW
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
