---
- hosts: worker,controlplane
  tasks:
  - name: Add machine entries in /etc/hosts 
    ansible.builtin.blockinfile:
      block: |
        192.168.100.10 controlplane controlplane.mkube 
        192.168.100.11 worker worker.mkube 
      path: /etc/hosts

- hosts: controlplane 
  roles:
    - controlplane

- hosts: controlplane
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "/vagrant/vagrant.key.rsa"
  tasks:
    - name: Copy kubeconfig file for later use by Headlamp
      copy: 
        src: /home/vagrant/.kube/conf
        dest: /vagrant/kubeconf

    - name: Change private key permissions
      file:
        path: "/vagrant/vagrant.key.rsa"
        mode: 0600

    - name: Run Join script 
      script: /home/vagrant/join.sh
      delegate_to: worker

- hosts: controlplane
  roles:
    - extras