---
- hosts: worker,controlplane 
  roles:
    - mkube

- hosts: controlplane 
  roles:
    - controlplane

- hosts: controlplane
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "/vagrant/vagrant.key.rsa"
  tasks:
    - name: Run Join script 
      script: /home/vagrant/join.sh
      delegate_to: worker

- hosts: controlplane
  roles:
    - extras